# Generated by Django 5.0.6 on 2024-06-19 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.client'),
        ),
    ]
