# Generated by Django 5.0.6 on 2024-06-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_entry_client_alter_exit_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='client',
        ),
        migrations.RemoveField(
            model_name='exit',
            name='date',
        ),
    ]
