# Generated by Django 5.0.6 on 2024-06-24 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_entry_client_remove_exit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
            preserve_default=False,
        ),
    ]
