# Generated by Django 5.0.6 on 2024-06-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_exit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
